
SHOW TABLES IN SCHEMA CHARGER_STATION_VEHICLE.STAGING;

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();


SELECT COUNT(*) FROM "CONNECTOR_TABLE_UPDATE";
SELECT COUNT(*) FROM "connector_table_update";