models:
  - name: fact_charger
    description: "Fact charger representing each public charging station"
    columns:
      - name: operator_id
        description: "Foreign key from dim operator"
        data_tests:
          - relationships:
              to: ref('dim_operator')
              field: operator_id

      - name: geo_id
        description: "Foreign key from dim_geo"
        data_tests:
          - relationships:
              to: ref('dim_geo')
              field: geo_id

      - name: station_id
        description: "varchar"

      - name: number_charging_points
        description: "integer"
        data_tests:
          - not_null

      - name: available_charging_points
        description: "integer"
        data_tests:
          - not_null

      - name: update_date
        description: "Date when updated data"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

      - name: created_date
        description: "Date when charger was created in Nobil"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
  - name: fact_connector
    description:  "Fact_connector representing connector for it's attribute and trans"
    columns:
      - name: conn_id
        description: "Foreign key from dim_connector_attribute_value"
        data_tests:
          - relationships: 
              to: ref('dim_connector_attribute_value')
              field: conn_id

      - name: station_id
        description: "varchar"

      - name: connector_nr
        desription: "integer"


  - name: fact_vehicle
    description: "Fact vehicle representing amount of vehicles"
    columns:
      - name: vehicle_id
        description: "Foreign key from dim_vehicle_in_traffic"
        data_tests:
          - relationships: 
              to: ref('dim_vehicle_in_traffic')
              field: vehicle_id

      - name: geo_id
        description: "Foreign key from dim_geo"
        data_tests:
          - relationships:
              to: ref('dim_geo')
              field: geo_id

      - name: year
        descrioption: "int"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number


  - name: dim_connector_attribute_value
    description: "Dimension table to describe charger connector for fact_charger"
    columns:
      - name: conn_id
        description: "Primary key. A surrogate key consisting of csmd.id, st.attrname, conn.attrname"
        data_tests:
          - unique
          - not_null
      - name: attribute_name
        descrioption: "varchar"
      - name: trans
        description: "varchar"


  - name: dim_geo
    description: "Dimension table to describe geological place for fact_charger and fact_vehicle"
    columns:
      - name: geo_id
        description: "Primary key. A surrogate key consisting of municipality, county, id"
        data_tests:
          - unique
          - not_null
      - name: municipality
        description: "varchar"
      - name: county
        description: "varchar"

  - name: dim_vehicle_in_traffic
    description: "Dimension table to describe numner of vehicle for fact_vehicle"
    columns:
      - name: vehicle_id
        description: "Primary key. A surrogate key consisting of id and fuel"
        data_tests:
          - unique
          - not_null
      - name: vehicle_in_traffic
        description: "int"
      - name: fuel
        deascription: "varchar"

  - name: dim_operator
    description: "Dimension table for operator for charger station"
    columns: 
      - name: operator_id
        description: "Primary key. A surrogate key consisting of operator"
        data_tests:
          - unique
          - not_null